require:
  - rubocop-haml
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - spec/**/*.haml
  NewCops: enable
  TargetRubyVersion: 2.6

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-haml.rb

Style/Documentation:
  Enabled: false
